# Generated by Django 3.0.2 on 2020-03-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200326_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
