# Generated by Django 3.0.4 on 2020-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200322_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activity', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('activity_intensity', models.CharField(choices=[('L', 'light'), ('M', 'moderate'), ('S', 'strenuous'), ('V', 'very strenuous')], default=0, max_length=1)),
            ],
        ),
    ]
